# Python Project - SBOM Generation
# Software Bill of Materials generation and vulnerability scanning
#
# This workflow:
#   - Generates CycloneDX SBOM
#   - Scans for vulnerabilities with Trivy
#   - Checks license compliance
#   - Uploads SARIF to GitHub Security tab
#
# Triggered by:
#   - Push to main branch
#   - Release creation
#   - Weekly schedule

name: SBOM

on:
  push:
    branches:
      - main
  release:
    types: [published]
  schedule:
    # Run weekly on Monday at 00:00 UTC
    - cron: '0 0 * * 1'

permissions: read-all

jobs:
  sbom:
    name: SBOM Generation & Scan
    uses: williaby/.github/.github/workflows/python-sbom.yml@main
    with:
      python-version: '3.12'
      fail-on-vulnerabilities: true
      severity-threshold: 'CRITICAL,HIGH'
      artifact-retention-days: 90
      forbidden-licenses: '["GPL-2.0-only", "GPL-2.0-or-later", "GPL-3.0-only", "GPL-3.0-or-later", "AGPL-3.0-only", "AGPL-3.0-or-later"]'
      fail-on-forbidden-licenses: false
    permissions:
      contents: read
      security-events: write
