# Python Project - OpenSSF Scorecard
# Evaluates repository security health using OpenSSF Scorecard
#
# This workflow:
#   - Runs OpenSSF Scorecard analysis
#   - Publishes results to OpenSSF REST API
#   - Uploads SARIF to GitHub Security tab
#
# Triggered by:
#   - Push to main branch
#   - Weekly schedule (Sunday at 00:00 UTC)

name: OpenSSF Scorecard

on:
  push:
    branches:
      - main
  schedule:
    # Run weekly on Sunday at 00:00 UTC
    - cron: '0 0 * * 0'

permissions:
  security-events: write
  id-token: write
  contents: read
  actions: read

jobs:
  scorecard:
    name: Scorecard Analysis
    uses: ByronWilliamsCPA/.github/.github/workflows/python-scorecard.yml@main
    with:
      publish-results: true
      upload-sarif: true
    permissions:
      security-events: write
      id-token: write
      contents: read
      actions: read
