# Python Project - PR Validation
# Comprehensive pull request validation
#
# This workflow:
#   - Validates PR title (conventional commits)
#   - Validates PR description
#   - Runs code quality checks
#   - Executes test suite
#   - Detects breaking changes
#   - Adds size labels
#
# Triggered by:
#   - Pull requests to main branch

name: PR Validation

on:
  pull_request:
    branches:
      - main
      - develop
    types:
      - opened
      - synchronize
      - reopened
      - edited

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  pr-validation:
    name: PR Validation
    uses: williaby/.github/.github/workflows/python-pr-validation.yml@main
    with:
      python-version: '3.12'
      source-directory: 'src'
      test-directory: 'tests'
      require-tests: true
      require-conventional-commits: true
      require-description: true
      min-description-length: 50
      check-breaking-changes: true
      add-size-labels: true
      coverage-threshold: 80
    permissions:
      contents: read
      pull-requests: write
      checks: write
